
stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN! Building app..."
    - mvn clean install -DskipTests=true

test-job:
  stage: test
  script:
    - echo "This job runs tests"
    - mvn test
