create table contact (id_contact integer generated by default as identity,
    address varchar(255), city varchar(255),
    email varchar(255) not null,
    firstname varchar(150) not null,
    phone varchar(50), psc varchar(30),
    region varchar(255),
    surname varchar(255) not null,
    primary key (id_contact));

create table form (id_form integer generated by default as identity,
    message varchar(255) not null,
    id_contact integer not null,
    primary key (id_form));

alter table form add constraint fk_messages foreign key (id_contact) references contact;